num_workers: 32
dicom:
  dir: "/zfs/wficai/pda/batch_2/"
  recursive: true
media:
  dir: "/scratch/dane2/dme/batch_2/"
  overwrite: true
metadata: 
  file: "/scratch/dane2/dme/metadata.jsonl"
  append: false
config: 
  file: "/scratch/dane2/dme/config.yml"
video: 
  extension: ".mp4"
  save_method_kwargs:
    encoding_format: "h264" # the encoding format passed to ffmpeg
    encoding_args: # any additional encoding options passed to ffmpeg
      pix_fmt: "yuv420p"
      options:
        crf: "17"
image:
  extension: ".png"
  save_method_kwargs:
    pil_writer_params: {}